[project]
name = "gaijin-store-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "python-dotenv>=1.2.1",
    "python-telegram-bot[job-queue]>=22.5",
    "requests>=2.32.5",
]
